name: 🚀 1. Deploy to Pro
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy to Pro
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer
        run: sudo apt-get update && sudo apt-get install -y composer

      - name: Validate Composer configuration
        run: composer validate

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist --verbose

      - name: 📂 Sync files to Staging
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 109.106.251.30
          username: u442793684.architecturedesigning
          password: AAaa11@@AA@open2code.com
          server-dir: /
